# Generated by Django 5.2.14 on 2026-06-27 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_request_id', models.CharField(db_index=True, help_text='Client-generated idempotency key (prevents double-charges on retry).', max_length=64, unique=True)),
                ('service_type', models.CharField(max_length=32)),
                ('account', models.CharField(max_length=128)),
                ('amount', models.PositiveIntegerField(help_text='Amount in UGX (no decimals).')),
                ('momo_network', models.CharField(choices=[('mtn', 'MTN MoMo'), ('airtel', 'Airtel Money')], default='mtn', max_length=16)),
                ('momo_phone', models.CharField(max_length=20)),
                ('pegasus_reference', models.CharField(blank=True, max_length=128)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('pegasus_response', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment transaction',
                'verbose_name_plural': 'Payment transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
