# Generated by Django 5.2.14 on 2026-05-31 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('enable_voice', models.BooleanField(default=True)),
                ('enable_orders', models.BooleanField(default=False)),
                ('enable_bookings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_model', models.CharField(default='gpt-4o', max_length=100)),
                ('realtime_model', models.CharField(default='gpt-4o-realtime-preview', max_length=100)),
                ('transcription_model', models.CharField(default='whisper-1', max_length=100)),
                ('tts_model', models.CharField(default='gpt-4o-mini-tts', max_length=100)),
                ('tts_voice', models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='coral', max_length=20)),
                ('realtime_voice', models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='coral', max_length=20)),
                ('system_prompt', models.TextField(default='You are ChaliAssistant, a helpful customer care AI for {company_name}. Answer accurately using the company knowledge base. Be polite and concise. If you cannot resolve an issue, offer to create a support ticket or escalate to a human agent.')),
                ('voice_system_prompt', models.TextField(default='You are ChaliAssistant on a voice call for {company_name}. Keep responses short and conversational. Use the knowledge base tools when needed.')),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.PositiveIntegerField(default=1024)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Allow AI to auto-create tickets when escalation is needed.')),
                ('enabled_tools', models.JSONField(blank=True, default=list, help_text='Tool names enabled for this company, e.g. search_knowledge_base, create_ticket.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='tenants.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('viewer', 'Viewer')], default='agent', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__name'],
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company', 'is_published'], name='tenants_kno_company_f87b3e_idx')],
            },
        ),
    ]
