# Generated by Django 5.2.14 on 2026-06-01 03:47

import django.db.models.deletion
import tenants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to=tenants.models.knowledge_source_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('pptx', 'PowerPoint'), ('txt', 'Plain Text')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_source_documents', to='tenants.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('slide_number', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='tenants.company')),
                ('legacy_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenants.knowledgedocument')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenants.knowledgesourcedocument')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgesourcedocument',
            index=models.Index(fields=['company', 'status', 'is_published'], name='tenants_kno_company_bd18ad_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesourcedocument',
            index=models.Index(fields=['company', 'content_hash'], name='tenants_kno_company_69bf19_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['company', 'is_active'], name='tenants_kno_company_34a386_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source_document', 'is_active'], name='tenants_kno_source__add2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['legacy_document', 'is_active'], name='tenants_kno_legacy__d8e2d1_idx'),
        ),
    ]
