# Generated by Django 5.2.14 on 2026-06-01 03:18

from django.db import migrations, models


def backfill_conversation_summary(apps, schema_editor):
    Conversation = apps.get_model('operations', 'Conversation')
    Message = apps.get_model('operations', 'Message')
    for conversation in Conversation.objects.all().iterator():
        messages = Message.objects.filter(conversation_id=conversation.id).order_by('-created_at')
        last = messages.first()
        conversation.message_count = messages.count()
        conversation.assistant_message_count = messages.filter(role='assistant').count()
        conversation.last_message_at = last.created_at if last else None
        if last:
            preview = last.text_content or last.audio_transcript or ''
            conversation.last_message_preview = preview[:240]
        else:
            conversation.last_message_preview = ''
        conversation.save(
            update_fields=[
                'message_count',
                'assistant_message_count',
                'last_message_at',
                'last_message_preview',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assistant_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_preview',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_conversation_summary, migrations.RunPython.noop),
    ]
