# Generated by Django 5.2.14 on 2026-07-12 03:38

import django.db.models.deletion
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_conversation_assistant_message_count_and_more'),
        ('tenants', '0007_update_ai_config_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rendering', 'Rendering'), ('extracting', 'Extracting'), ('review', 'Ready for Review'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('render_mode', models.CharField(choices=[('static', 'Static HTML'), ('headless', 'Headless browser'), ('api', 'Captured API')], default='static', max_length=20)),
                ('raw_html', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=operations.models.catalog_import_screenshot_upload_path)),
                ('captured_api', models.JSONField(blank=True, default=dict)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_imports', to='tenants.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='tenants.company')),
            ],
            options={
                'verbose_name_plural': 'menu categories',
                'ordering': ['company__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to=operations.models.menu_item_image_upload_path)),
                ('source_image_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave empty when the item is available at all branches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='operations.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='operations.menucategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='tenants.company')),
            ],
            options={
                'ordering': ['company__name', 'category__sort_order', 'category__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'is_active'], name='operations__company_2f8240_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='ops_branch_company_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='catalogimportjob',
            index=models.Index(fields=['company', 'status'], name='operations__company_ecd16b_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogimportjob',
            index=models.Index(fields=['source_url'], name='operations__source__6f883b_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['company', 'sort_order'], name='operations__company_aa87cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='ops_menu_cat_company_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['company', 'status', 'is_available'], name='operations__company_f1ccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['company', 'needs_review'], name='operations__company_b0c346_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['company', 'is_featured'], name='operations__company_b99c2c_idx'),
        ),
    ]
